-- MealPro Phase 3 central catalog schema
-- Designed for Supabase/Postgres. Public catalog is read-only to app clients;
-- ingestion should run with a privileged server/service role.

create table if not exists public.products (
  id text primary key,
  barcode text,
  name text not null,
  brand text not null default '',
  pack numeric not null default 0,
  unit text not null default 'kom',
  search_text text not null default '',
  updated_at timestamptz not null default now()
);

create index if not exists products_barcode_idx on public.products(barcode);
create index if not exists products_search_idx on public.products using gin (to_tsvector('simple', search_text));

create table if not exists public.offers (
  id text primary key,
  product_id text not null references public.products(id) on delete cascade,
  store text not null,
  price numeric(10,2) not null check (price > 0),
  pack numeric not null default 0,
  unit text not null default 'kom',
  price_per_100 numeric(12,4),
  on_sale boolean not null default false,
  observed_at timestamptz not null default now()
);

create index if not exists offers_product_id_idx on public.offers(product_id);
create index if not exists offers_store_idx on public.offers(store);
create index if not exists offers_price_idx on public.offers(price);

create table if not exists public.price_history (
  id bigint generated by default as identity primary key,
  offer_id text not null,
  product_id text not null,
  store text not null,
  price numeric(10,2) not null check (price > 0),
  previous_price numeric(10,2) not null check (previous_price > 0),
  on_sale boolean not null default false,
  recorded_at timestamptz not null default now()
);

create index if not exists price_history_offer_time_idx on public.price_history(offer_id, recorded_at desc);
create index if not exists price_history_product_time_idx on public.price_history(product_id, recorded_at desc);

create table if not exists public.catalog_syncs (
  id bigint generated by default as identity primary key,
  source text not null default 'cijene.dev',
  archive_date date,
  archive_url text,
  products_count integer not null default 0,
  offers_count integer not null default 0,
  price_changes integer not null default 0,
  removed_offers integer not null default 0,
  missing_chains jsonb not null default '[]'::jsonb,
  status text not null check (status in ('running','success','partial','failed')),
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

alter table public.products enable row level security;
alter table public.offers enable row level security;
alter table public.price_history enable row level security;
alter table public.catalog_syncs enable row level security;

-- Catalog can be read by app clients. Writes are intentionally not granted here;
-- backend ingestion uses the service role and bypasses RLS.
create policy "public catalog products read"
on public.products for select
to anon, authenticated
using (true);

create policy "public catalog offers read"
on public.offers for select
to anon, authenticated
using (true);

-- Clients may read synchronization status, but never write it.
drop policy if exists "public catalog sync status read" on public.catalog_syncs;
create policy "public catalog sync status read"
on public.catalog_syncs for select
to anon, authenticated
using (true);

-- Idempotent policy for deployments where the base migration already ran.
do $$ begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public' and tablename='catalog_syncs'
      and policyname='public catalog sync status read'
  ) then
    create policy "public catalog sync status read"
    on public.catalog_syncs for select
    to anon, authenticated
    using (true);
  end if;
end $$;
